name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, 'ci skip') }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: https://codeberg.org/mlugg/setup-zig@v2

      - name: Install MPSS
        run: |
          apt-get update
          apt-get install -y unzip curl
          curl -fsSL "https://drive.kbz8.me/dav/public-files/KSKeiOKxnFPyfws/mpss.zip" -o /tmp/mpss.zip
          rm -rf /opt/mpss
          unzip -q /tmp/mpss.zip -d /opt
          chmod -R a+rX /opt/mpss
          test -d /opt/mpss/3.8.6/sysroots/k1om-mpss-linux/bin
          echo "/opt/mpss/3.8.6/sysroots/k1om-mpss-linux/bin" >> "$GITHUB_PATH"

      - name: Building Ape
        run: zig build ape --release=safe

      - name: Building Soft
        run: zig build soft --release=safe

      - name: Building Flint
        run: zig build flint --release=safe

      - name: Building Phi
        run: zig build phi --release=safe

      - name: Generating docs
        run: zig build docs

      - name: Deploying docs
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.SFTP_HOST_DOCS }}
          remote-user: ${{ secrets.SFTP_USER_DOCS }}
          remote-password: ${{ secrets.SFTP_PASSWORD_DOCS }}
          remote-port: 6969
          local-path: "./zig-out/docs"
          remote-path: "/www"
          sync: full
