name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, 'ci skip') }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: https://codeberg.org/mlugg/setup-zig@v2

      - name: Building
        run: zig build soft

      - name: Generating docs
        run: zig build docs

      - name: Deploying docs
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.SFTP_HOST_DOCS }}
          remote-user: ${{ secrets.SFTP_USER_DOCS }}
          remote-password: ${{ secrets.SFTP_PASSWORD_DOCS }}
          remote-port: 6969
          local-path: "./zig-out/docs"
          remote-path: "/www"
          sync: full
