name: Docs and IR

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, 'ci skip') }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: https://codeberg.org/mlugg/setup-zig@v2

      - name: Check formatting
        run: zig fmt --check src/

      - name: ZLint pass
        run: |
          curl -fsSL https://raw.githubusercontent.com/DonIsaac/zlint/refs/heads/main/tasks/install.sh | bash
          zlint --deny-warnings

      - name: Testing IR
        run: zig build test-ir

      - name: Generating docs
        run: zig build docs

      - name: Deploying docs
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.SFTP_HOST_DOCS }}
          remote-user: ${{ secrets.SFTP_USER_DOCS }}
          remote-password: ${{ secrets.SFTP_PASSWORD_DOCS }}
          remote-port: 6969
          local-path: "./zig-out/docs"
          remote-path: "/www"
          sync: full

      - name: Generating IR docs
        run: zig build docs-ir

      - name: Deploying IR docs
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.SFTP_HOST_DOCS_IR }}
          remote-user: ${{ secrets.SFTP_USER_DOCS_IR }}
          remote-password: ${{ secrets.SFTP_PASSWORD_DOCS_IR  }}
          remote-port: 6969
          local-path: "./zig-out/docs-ir"
          remote-path: "/www"
          sync: full
