name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'test skip')"

    steps:
      - uses: actions/checkout@v4
      - uses: https://codeberg.org/mlugg/setup-zig@v2

      - name: Install MPSS
        run: |
          set -euxo pipefail

          apt-get update
          apt-get install -y unzip curl

          MPSS_URL="https://drive.kbz8.me/dav/public-files/KSKeiOKxnFPyfws/mpss.zip"
          MPSS_ZIP="/tmp/mpss.zip"
          MPSS_BIN="/opt/mpss/3.8.6/sysroots/k1om-mpss-linux/bin"

          curl --fail --location --show-error --progress-bar "$MPSS_URL" -o "$MPSS_ZIP"

          size="$(stat -c%s "$MPSS_ZIP")"
          test "$size" -gt 300000000

          unzip -t "$MPSS_ZIP" >/dev/null

          rm -rf /opt/mpss
          unzip -q "$MPSS_ZIP" -d /opt
          chmod -R a+rX /opt/mpss

          test -d "$MPSS_BIN"

          # Append as fallback for following CI steps.
          echo "PATH=$PATH:$MPSS_BIN" >> "$GITHUB_ENV"

          echo "MPSS installed."

      - name: Check MPSS PATH
        run: |
          echo "$PATH"
          ls -la /opt/mpss/3.8.6/sysroots/k1om-mpss-linux/bin | head -50

      - name: Installing dependencies
        run: apt update && apt install spirv-tools

      - name: Ape Tests
        run: zig build test-ape --release=safe

      - name: Soft Tests
        run: zig build test-soft --release=safe

      - name: Flint Tests
        run: zig build test-flint --release=safe

      - name: Phi Tests
        run: zig build test-phi --release=safe

      - name: IR Tests
        run: zig build test-ir --release=safe
