name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'test skip')"

    steps:
    - uses: actions/checkout@v4
    - uses: https://codeberg.org/mlugg/setup-zig@v2

    - name: Install MPSS
      run: |
        apt-get update
        apt-get install -y unzip curl
        curl -fsSL "https://drive.kbz8.me/dav/public-files/KSKeiOKxnFPyfws/mpss.zip" -o /tmp/mpss.zip
        rm -rf /opt/mpss
        unzip -q /tmp/mpss.zip -d /opt
        chmod -R a+rX /opt/mpss
        test -d /opt/mpss/3.8.6/sysroots/k1om-mpss-linux/bin
        echo "/opt/mpss/3.8.6/sysroots/k1om-mpss-linux/bin" >> "$GITHUB_PATH"

    - name: Ape Tests
      run: zig build test-ape --release=safe

    - name: Soft Tests
      run: zig build test-soft --release=safe

    - name: Flint Tests
      run: zig build test-flint --release=safe

    - name: Phi Tests
      run: zig build test-phi --release=safe
