pub const magic_number: u32 = 0x07230203;
pub const byte_swapped_magic_number: u32 = 0x03022307;
pub const header_word_count: usize = 5;

pub const Opcode = enum(u32) {
    nop = 0,
    undef = 1,
    source_continued = 2,
    source = 3,
    source_extension = 4,
    name = 5,
    member_name = 6,
    string = 7,
    line = 8,

    extension = 10,
    ext_inst_import = 11,
    ext_inst = 12,

    memory_model = 14,
    entry_point = 15,
    execution_mode = 16,
    capability = 17,

    type_void = 19,
    type_bool = 20,
    type_int = 21,
    type_float = 22,
    type_vector = 23,
    type_matrix = 24,
    type_image = 25,
    type_sampler = 26,
    type_sampled_image = 27,
    type_array = 28,
    type_runtime_array = 29,
    type_struct = 30,
    type_opaque = 31,
    type_pointer = 32,
    type_function = 33,
    type_event = 34,
    type_device_event = 35,
    type_reserve_id = 36,
    type_queue = 37,
    type_pipe = 38,
    type_forward_pointer = 39,

    constant_true = 41,
    constant_false = 42,
    constant = 43,
    constant_composite = 44,
    constant_sampler = 45,
    constant_null = 46,

    spec_constant_true = 48,
    spec_constant_false = 49,
    spec_constant = 50,
    spec_constant_composite = 51,
    spec_constant_op = 52,

    function = 54,
    function_parameter = 55,
    function_end = 56,
    function_call = 57,

    variable = 59,
    image_texel_pointer = 60,
    load = 61,
    store = 62,
    copy_memory = 63,
    copy_memory_sized = 64,
    access_chain = 65,
    in_bounds_access_chain = 66,
    ptr_access_chain = 67,
    array_length = 68,
    generic_ptr_mem_semantics = 69,
    in_bounds_ptr_access_chain = 70,
    decorate = 71,
    member_decorate = 72,
    decoration_group = 73,
    group_decorate = 74,
    group_member_decorate = 75,

    vector_extract_dynamic = 77,
    vector_insert_dynamic = 78,
    vector_shuffle = 79,
    composite_construct = 80,
    composite_extract = 81,
    composite_insert = 82,
    copy_object = 83,
    transpose = 84,

    sampled_image = 86,
    image_sample_implicit_lod = 87,
    image_sample_explicit_lod = 88,
    image_sample_dref_implicit_lod = 89,
    image_sample_dref_explicit_lod = 90,
    image_sample_proj_implicit_lod = 91,
    image_sample_proj_explicit_lod = 92,
    image_sample_proj_dref_implicit_lod = 93,
    image_sample_proj_dref_explicit_lod = 94,
    image_fetch = 95,
    image_gather = 96,
    image_dref_gather = 97,
    image_read = 98,
    image_write = 99,
    image = 100,
    image_query_format = 101,
    image_query_order = 102,
    image_query_size_lod = 103,
    image_query_size = 104,
    image_query_lod = 105,
    image_query_levels = 106,
    image_query_samples = 107,

    convert_f_to_u = 109,
    convert_f_to_s = 110,
    convert_s_to_f = 111,
    convert_u_to_f = 112,
    u_convert = 113,
    s_convert = 114,
    f_convert = 115,
    quantize_to_f16 = 116,
    convert_ptr_to_u = 117,
    sat_convert_s_to_u = 118,
    sat_convert_u_to_s = 119,
    convert_u_to_ptr = 120,
    ptr_cast_to_generic = 121,
    generic_cast_to_ptr = 122,
    generic_cast_to_ptr_explicit = 123,
    bitcast = 124,

    s_negate = 126,
    f_negate = 127,
    i_add = 128,
    f_add = 129,
    i_sub = 130,
    f_sub = 131,
    i_mul = 132,
    f_mul = 133,
    u_div = 134,
    s_div = 135,
    f_div = 136,
    u_mod = 137,
    s_rem = 138,
    s_mod = 139,
    f_rem = 140,
    f_mod = 141,
    vector_times_scalar = 142,
    matrix_times_scalar = 143,
    vector_times_matrix = 144,
    matrix_times_vector = 145,
    matrix_times_matrix = 146,
    outer_product = 147,
    dot = 148,
    i_add_carry = 149,
    i_sub_borrow = 150,
    u_mul_extended = 151,
    s_mul_extended = 152,

    any = 154,
    all = 155,
    is_nan = 156,
    is_inf = 157,
    is_finite = 158,
    is_normal = 159,
    sign_bit_set = 160,
    less_or_greater = 161,
    ordered = 162,
    unordered = 163,
    logical_equal = 164,
    logical_not_equal = 165,
    logical_or = 166,
    logical_and = 167,
    logical_not = 168,
    select = 169,
    i_equal = 170,
    i_not_equal = 171,
    u_greater_than = 172,
    s_greater_than = 173,
    u_greater_than_equal = 174,
    s_greater_than_equal = 175,
    u_less_than = 176,
    s_less_than = 177,
    u_less_than_equal = 178,
    s_less_than_equal = 179,
    f_ord_equal = 180,
    f_unord_equal = 181,
    f_ord_not_equal = 182,
    f_unord_not_equal = 183,
    f_ord_less_than = 184,
    f_unord_less_than = 185,
    f_ord_greater_than = 186,
    f_unord_greater_than = 187,
    f_ord_less_than_equal = 188,
    f_unord_less_than_equal = 189,
    f_ord_greater_than_equal = 190,
    f_unord_greater_than_equal = 191,

    shift_right_logical = 194,
    shift_right_arithmetic = 195,
    shift_left_logical = 196,
    bitwise_or = 197,
    bitwise_xor = 198,
    bitwise_and = 199,
    not = 200,
    bit_field_insert = 201,
    bit_field_s_extract = 202,
    bit_field_u_extract = 203,
    bit_reverse = 204,
    bit_count = 205,

    d_pdx = 207,
    d_pdy = 208,
    fwidth = 209,
    d_pdx_fine = 210,
    d_pdy_fine = 211,
    fwidth_fine = 212,
    d_pdx_coarse = 213,
    d_pdy_coarse = 214,
    fwidth_coarse = 215,

    emit_vertex = 218,
    end_primitive = 219,
    emit_stream_vertex = 220,
    end_stream_primitive = 221,

    control_barrier = 224,
    memory_barrier = 225,

    atomic_load = 227,
    atomic_store = 228,
    atomic_exchange = 229,
    atomic_compare_exchange = 230,
    atomic_compare_exchange_weak = 231,
    atomic_i_increment = 232,
    atomic_i_decrement = 233,
    atomic_i_add = 234,
    atomic_i_sub = 235,
    atomic_s_min = 236,
    atomic_u_min = 237,
    atomic_s_max = 238,
    atomic_u_max = 239,
    atomic_and = 240,
    atomic_or = 241,
    atomic_xor = 242,

    phi = 245,
    loop_merge = 246,
    selection_merge = 247,
    label = 248,
    branch = 249,
    branch_conditional = 250,
    @"switch" = 251,
    kill = 252,
    return_ = 253,
    return_value = 254,
    @"unreachable" = 255,
    lifetime_start = 256,
    lifetime_stop = 257,

    group_async_copy = 259,
    group_wait_events = 260,
    group_all = 261,
    group_any = 262,
    group_broadcast = 263,
    group_i_add = 264,
    group_f_add = 265,
    group_f_min = 266,
    group_u_min = 267,
    group_s_min = 268,
    group_f_max = 269,
    group_u_max = 270,
    group_s_max = 271,

    read_pipe = 274,
    write_pipe = 275,
    reserved_read_pipe = 276,
    reserved_write_pipe = 277,
    reserve_read_pipe_packets = 278,
    reserve_write_pipe_packets = 279,
    commit_read_pipe = 280,
    commit_write_pipe = 281,
    is_valid_reserve_id = 282,
    get_num_pipe_packets = 283,
    get_max_pipe_packets = 284,
    group_reserve_read_pipe_packets = 285,
    group_reserve_write_pipe_packets = 286,
    group_commit_read_pipe = 287,
    group_commit_write_pipe = 288,

    enqueue_marker = 291,
    enqueue_kernel = 292,
    get_kernel_n_drange_sub_group_count = 293,
    get_kernel_n_drange_max_sub_group_size = 294,
    get_kernel_work_group_size = 295,
    get_kernel_preferred_work_group_size_multiple = 296,
    retain_event = 297,
    release_event = 298,
    create_user_event = 299,
    is_valid_event = 300,
    set_user_event_status = 301,
    capture_event_profiling_info = 302,
    get_default_queue = 303,
    build_nd_range = 304,
    image_sparse_sample_implicit_lod = 305,
    image_sparse_sample_explicit_lod = 306,
    image_sparse_sample_dref_implicit_lod = 307,
    image_sparse_sample_dref_explicit_lod = 308,
    image_sparse_sample_proj_implicit_lod = 309,
    image_sparse_sample_proj_explicit_lod = 310,
    image_sparse_sample_proj_dref_implicit_lod = 311,
    image_sparse_sample_proj_dref_explicit_lod = 312,
    image_sparse_fetch = 313,
    image_sparse_gather = 314,
    image_sparse_dref_gather = 315,
    image_sparse_texels_resident = 316,
    no_line = 317,
    atomic_flag_test_and_set = 318,
    atomic_flag_clear = 319,
    image_sparse_read = 320,
    size_of = 321,
    type_pipe_storage = 322,
    constant_pipe_storage = 323,
    create_pipe_from_pipe_storage = 324,
    get_kernel_local_size_for_subgroup_count = 325,
    get_kernel_max_num_subgroups = 326,
    type_named_barrier = 327,
    named_barrier_initialize = 328,
    memory_named_barrier = 329,
    module_processed = 330,
    execution_mode_id = 331,
    decorate_id = 332,
    group_non_uniform_elect = 333,
    group_non_uniform_all = 334,
    group_non_uniform_any = 335,
    group_non_uniform_all_equal = 336,
    group_non_uniform_broadcast = 337,
    group_non_uniform_broadcast_first = 338,
    group_non_uniform_ballot = 339,
    group_non_uniform_inverse_ballot = 340,
    group_non_uniform_ballot_bit_extract = 341,
    group_non_uniform_ballot_bit_count = 342,
    group_non_uniform_ballot_find_lsb = 343,
    group_non_uniform_ballot_find_msb = 344,
    group_non_uniform_shuffle = 345,
    group_non_uniform_shuffle_xor = 346,
    group_non_uniform_shuffle_up = 347,
    group_non_uniform_shuffle_down = 348,
    group_non_uniform_i_add = 349,
    group_non_uniform_f_add = 350,
    group_non_uniform_i_mul = 351,
    group_non_uniform_f_mul = 352,
    group_non_uniform_s_min = 353,
    group_non_uniform_u_min = 354,
    group_non_uniform_f_min = 355,
    group_non_uniform_s_max = 356,
    group_non_uniform_u_max = 357,
    group_non_uniform_f_max = 358,
    group_non_uniform_bitwise_and = 359,
    group_non_uniform_bitwise_or = 360,
    group_non_uniform_bitwise_xor = 361,
    group_non_uniform_logical_and = 362,
    group_non_uniform_logical_or = 363,
    group_non_uniform_logical_xor = 364,
    group_non_uniform_quad_broadcast = 365,
    group_non_uniform_quad_swap = 366,

    copy_logical = 400,
    ptr_equal = 401,
    ptr_not_equal = 402,
    ptr_diff = 403,

    color_attachment_read_ext = 4160,
    depth_attachment_read_ext = 4161,
    stencil_attachment_read_ext = 4162,
    type_tensor_arm = 4163,
    tensor_read_arm = 4164,
    tensor_write_arm = 4165,
    tensor_query_size_arm = 4166,

    graph_constant_arm = 4181,
    graph_entry_point_arm = 4182,
    graph_arm = 4183,
    graph_input_arm = 4184,
    graph_set_output_arm = 4185,
    graph_end_arm = 4186,

    type_graph_arm = 4190,

    bitcast_extract_ext = 4195,

    terminate_invocation = 4416,
    type_untyped_pointer_khr = 4417,
    untyped_variable_khr = 4418,
    untyped_access_chain_khr = 4419,
    untyped_in_bounds_access_chain_khr = 4420,
    subgroup_ballot_khr = 4421,
    subgroup_first_invocation_khr = 4422,
    untyped_ptr_access_chain_khr = 4423,
    untyped_in_bounds_ptr_access_chain_khr = 4424,
    untyped_array_length_khr = 4425,
    untyped_prefetch_khr = 4426,
    fma_khr = 4427,
    subgroup_all_khr = 4428,
    subgroup_any_khr = 4429,
    subgroup_all_equal_khr = 4430,
    group_non_uniform_rotate_khr = 4431,
    subgroup_read_invocation_khr = 4432,
    ext_inst_with_forward_refs_khr = 4433,
    untyped_group_async_copy_khr = 4434,

    trace_ray_khr = 4445,
    execute_callable_khr = 4446,
    convert_u_to_acceleration_structure_khr = 4447,
    ignore_intersection_khr = 4448,
    terminate_ray_khr = 4449,
    s_dot = 4450,
    u_dot = 4451,
    su_dot = 4452,
    s_dot_acc_sat = 4453,
    u_dot_acc_sat = 4454,
    su_dot_acc_sat = 4455,
    type_cooperative_matrix_khr = 4456,
    cooperative_matrix_load_khr = 4457,
    cooperative_matrix_store_khr = 4458,
    cooperative_matrix_mul_add_khr = 4459,
    cooperative_matrix_length_khr = 4460,
    constant_composite_replicate_ext = 4461,
    spec_constant_composite_replicate_ext = 4462,
    composite_construct_replicate_ext = 4463,

    type_ray_query_khr = 4472,
    ray_query_initialize_khr = 4473,
    ray_query_terminate_khr = 4474,
    ray_query_generate_intersection_khr = 4475,
    ray_query_confirm_intersection_khr = 4476,
    ray_query_proceed_khr = 4477,

    ray_query_get_intersection_type_khr = 4479,
    image_sample_weighted_qcom = 4480,
    image_box_filter_qcom = 4481,
    image_block_match_ssd_qcom = 4482,
    image_block_match_sad_qcom = 4483,

    bit_cast_array_qcom = 4497,

    image_block_match_window_ssd_qcom = 4500,
    image_block_match_window_sad_qcom = 4501,
    image_block_match_gather_ssd_qcom = 4502,
    image_block_match_gather_sad_qcom = 4503,

    composite_construct_coop_mat_qcom = 4540,
    composite_extract_coop_mat_qcom = 4541,
    extract_sub_array_qcom = 4542,

    image_gather_qcom = 4545,

    group_i_add_non_uniform_amd = 5000,
    group_f_add_non_uniform_amd = 5001,
    group_f_min_non_uniform_amd = 5002,
    group_u_min_non_uniform_amd = 5003,
    group_s_min_non_uniform_amd = 5004,
    group_f_max_non_uniform_amd = 5005,
    group_u_max_non_uniform_amd = 5006,
    group_s_max_non_uniform_amd = 5007,

    fragment_mask_fetch_amd = 5011,
    fragment_fetch_amd = 5012,

    read_clock_khr = 5056,

    allocate_node_payloads_amdx = 5074,
    enqueue_node_payloads_amdx = 5075,
    type_node_payload_array_amdx = 5076,

    finish_writing_node_payload_amdx = 5078,

    node_payload_array_length_amdx = 5090,

    is_node_payload_valid_amdx = 5101,

    constant_string_amdx = 5103,
    spec_constant_string_amdx = 5104,

    group_non_uniform_quad_all_khr = 5110,
    group_non_uniform_quad_any_khr = 5111,

    type_buffer_ext = 5115,

    buffer_pointer_ext = 5119,

    abort_khr = 5121,

    untyped_image_texel_pointer_ext = 5126,
    member_decorate_id_ext = 5127,

    constant_size_of_ext = 5129,

    constant_data_khr = 5147,
    spec_constant_data_khr = 5148,

    poison_khr = 5158,
    freeze_khr = 5159,

    hit_object_record_hit_motion_nv = 5249,
    hit_object_record_hit_with_index_motion_nv = 5250,
    hit_object_record_miss_motion_nv = 5251,
    hit_object_get_world_to_object_nv = 5252,
    hit_object_get_object_to_world_nv = 5253,
    hit_object_get_object_ray_direction_nv = 5254,
    hit_object_get_object_ray_origin_nv = 5255,
    hit_object_trace_ray_motion_nv = 5256,
    hit_object_get_shader_record_buffer_handle_nv = 5257,
    hit_object_get_shader_binding_table_record_index_nv = 5258,
    hit_object_record_empty_nv = 5259,
    hit_object_trace_ray_nv = 5260,
    hit_object_record_hit_nv = 5261,
    hit_object_record_hit_with_index_nv = 5262,
    hit_object_record_miss_nv = 5263,
    hit_object_execute_shader_nv = 5264,
    hit_object_get_current_time_nv = 5265,
    hit_object_get_attributes_nv = 5266,
    hit_object_get_hit_kind_nv = 5267,
    hit_object_get_primitive_index_nv = 5268,
    hit_object_get_geometry_index_nv = 5269,
    hit_object_get_instance_id_nv = 5270,
    hit_object_get_instance_custom_index_nv = 5271,
    hit_object_get_world_ray_direction_nv = 5272,
    hit_object_get_world_ray_origin_nv = 5273,
    hit_object_get_ray_t_max_nv = 5274,
    hit_object_get_ray_t_min_nv = 5275,
    hit_object_is_empty_nv = 5276,
    hit_object_is_hit_nv = 5277,
    hit_object_is_miss_nv = 5278,
    reorder_thread_with_hit_object_nv = 5279,
    reorder_thread_with_hint_nv = 5280,
    type_hit_object_nv = 5281,

    image_sample_footprint_nv = 5283,

    type_vector_id_ext = 5288,
    cooperative_vector_matrix_mul_nv = 5289,
    cooperative_vector_outer_product_accumulate_nv = 5290,
    cooperative_vector_reduce_sum_accumulate_nv = 5291,
    cooperative_vector_matrix_mul_add_nv = 5292,
    cooperative_matrix_convert_use_ext = 5293,
    emit_mesh_tasks_ext = 5294,
    set_mesh_outputs_ext = 5295,
    group_non_uniform_partition_ext = 5296,

    write_packed_primitive_indices4x8_nv = 5299,
    fetch_micro_triangle_vertex_position_nv = 5300,
    fetch_micro_triangle_vertex_barycentric_nv = 5301,
    cooperative_vector_load_nv = 5302,
    cooperative_vector_store_nv = 5303,
    hit_object_record_from_query_ext = 5304,
    hit_object_record_miss_ext = 5305,
    hit_object_record_miss_motion_ext = 5306,
    hit_object_get_intersection_triangle_vertex_positions_ext = 5307,
    hit_object_get_ray_flags_ext = 5308,
    hit_object_set_shader_binding_table_record_index_ext = 5309,
    hit_object_reorder_execute_shader_ext = 5310,
    hit_object_trace_reorder_execute_ext = 5311,
    hit_object_trace_motion_reorder_execute_ext = 5312,
    type_hit_object_ext = 5313,
    reorder_thread_with_hint_ext = 5314,
    reorder_thread_with_hit_object_ext = 5315,
    hit_object_trace_ray_ext = 5316,
    hit_object_trace_ray_motion_ext = 5317,
    hit_object_record_empty_ext = 5318,
    hit_object_execute_shader_ext = 5319,
    hit_object_get_current_time_ext = 5320,
    hit_object_get_attributes_ext = 5321,
    hit_object_get_hit_kind_ext = 5322,
    hit_object_get_primitive_index_ext = 5323,
    hit_object_get_geometry_index_ext = 5324,
    hit_object_get_instance_id_ext = 5325,
    hit_object_get_instance_custom_index_ext = 5326,
    hit_object_get_object_ray_origin_ext = 5327,
    hit_object_get_object_ray_direction_ext = 5328,
    hit_object_get_world_ray_direction_ext = 5329,
    hit_object_get_world_ray_origin_ext = 5330,
    hit_object_get_object_to_world_ext = 5331,
    hit_object_get_world_to_object_ext = 5332,
    hit_object_get_ray_t_max_ext = 5333,
    report_intersection_khr = 5334,
    ignore_intersection_nv = 5335,
    terminate_ray_nv = 5336,
    trace_nv = 5337,
    trace_motion_nv = 5338,
    trace_ray_motion_nv = 5339,
    ray_query_get_intersection_triangle_vertex_positions_khr = 5340,
    type_acceleration_structure_khr = 5341,

    execute_callable_nv = 5344,
    ray_query_get_intersection_cluster_id_nv = 5345,
    hit_object_get_cluster_id_nv = 5346,
    hit_object_get_ray_t_min_ext = 5347,
    hit_object_get_shader_binding_table_record_index_ext = 5348,
    hit_object_get_shader_record_buffer_handle_ext = 5349,
    hit_object_is_empty_ext = 5350,
    hit_object_is_hit_ext = 5351,
    hit_object_is_miss_ext = 5352,

    type_cooperative_matrix_nv = 5358,
    cooperative_matrix_load_nv = 5359,
    cooperative_matrix_store_nv = 5360,
    cooperative_matrix_mul_add_nv = 5361,
    cooperative_matrix_length_nv = 5362,
    cooperative_matrix_get_coordinate_ext = 5363,
    begin_invocation_interlock_ext = 5364,
    end_invocation_interlock_ext = 5365,
    cooperative_matrix_reduce_ext = 5366,
    cooperative_matrix_load_tensor_nv = 5367,
    cooperative_matrix_store_tensor_nv = 5368,
    cooperative_matrix_per_element_op_ext = 5369,
    type_tensor_layout_nv = 5370,
    type_tensor_view_nv = 5371,
    create_tensor_layout_nv = 5372,
    tensor_layout_set_dimension_nv = 5373,
    tensor_layout_set_stride_nv = 5374,
    tensor_layout_slice_nv = 5375,
    tensor_layout_set_clamp_value_nv = 5376,
    create_tensor_view_nv = 5377,
    tensor_view_set_dimension_nv = 5378,
    tensor_view_set_stride_nv = 5379,
    demote_to_helper_invocation = 5380,
    is_helper_invocation_ext = 5381,
    tensor_view_set_clip_nv = 5382,

    tensor_layout_set_block_size_nv = 5384,

    cooperative_matrix_transpose_nv = 5390,
    convert_u_to_image_nv = 5391,
    convert_u_to_sampler_nv = 5392,
    convert_image_to_u_nv = 5393,
    convert_sampler_to_u_nv = 5394,
    convert_u_to_sampled_image_nv = 5395,
    convert_sampled_image_to_u_nv = 5396,
    sampler_image_addressing_mode_nv = 5397,
    raw_access_chain_nv = 5398,

    ray_query_get_intersection_sphere_position_nv = 5427,
    ray_query_get_intersection_sphere_radius_nv = 5428,
    ray_query_get_intersection_lss_positions_nv = 5429,
    ray_query_get_intersection_lss_radii_nv = 5430,
    ray_query_get_intersection_lss_hit_value_nv = 5431,
    hit_object_get_sphere_position_nv = 5432,
    hit_object_get_sphere_radius_nv = 5433,
    hit_object_get_lss_positions_nv = 5434,
    hit_object_get_lss_radii_nv = 5435,
    hit_object_is_sphere_hit_nv = 5436,
    hit_object_is_lss_hit_nv = 5437,
    ray_query_is_sphere_hit_nv = 5438,
    ray_query_is_lss_hit_nv = 5439,

    subgroup_shuffle_intel = 5571,
    subgroup_shuffle_down_intel = 5572,
    subgroup_shuffle_up_intel = 5573,
    subgroup_shuffle_xor_intel = 5574,
    subgroup_block_read_intel = 5575,
    subgroup_block_write_intel = 5576,
    subgroup_image_block_read_intel = 5577,
    subgroup_image_block_write_intel = 5578,

    subgroup_image_media_block_read_intel = 5580,
    subgroup_image_media_block_write_intel = 5581,

    u_count_leading_zeros_intel = 5585,
    u_count_trailing_zeros_intel = 5586,
    abs_i_sub_intel = 5587,
    abs_u_sub_intel = 5588,
    i_add_sat_intel = 5589,
    u_add_sat_intel = 5590,
    i_average_intel = 5591,
    u_average_intel = 5592,
    i_average_rounded_intel = 5593,
    u_average_rounded_intel = 5594,
    i_sub_sat_intel = 5595,
    u_sub_sat_intel = 5596,
    i_mul32x16_intel = 5597,
    u_mul32x16_intel = 5598,

    constant_function_pointer_intel = 5600,
    function_pointer_call_intel = 5601,

    asm_target_intel = 5609,
    asm_intel = 5610,
    asm_call_intel = 5611,

    atomic_f_min_ext = 5614,
    atomic_f_max_ext = 5615,

    assume_true_khr = 5630,
    expect_khr = 5631,
    decorate_string = 5632,
    member_decorate_string = 5633,

    vme_image_intel = 5699,
    type_vme_image_intel = 5700,
    type_avc_ime_payload_intel = 5701,
    type_avc_ref_payload_intel = 5702,
    type_avc_sic_payload_intel = 5703,
    type_avc_mce_payload_intel = 5704,
    type_avc_mce_result_intel = 5705,
    type_avc_ime_result_intel = 5706,
    type_avc_ime_result_single_reference_streamout_intel = 5707,
    type_avc_ime_result_dual_reference_streamout_intel = 5708,
    type_avc_ime_single_reference_streamin_intel = 5709,
    type_avc_ime_dual_reference_streamin_intel = 5710,
    type_avc_ref_result_intel = 5711,
    type_avc_sic_result_intel = 5712,
    subgroup_avc_mce_get_default_inter_base_multi_reference_penalty_intel = 5713,
    subgroup_avc_mce_set_inter_base_multi_reference_penalty_intel = 5714,
    subgroup_avc_mce_get_default_inter_shape_penalty_intel = 5715,
    subgroup_avc_mce_set_inter_shape_penalty_intel = 5716,
    subgroup_avc_mce_get_default_inter_direction_penalty_intel = 5717,
    subgroup_avc_mce_set_inter_direction_penalty_intel = 5718,
    subgroup_avc_mce_get_default_intra_luma_shape_penalty_intel = 5719,
    subgroup_avc_mce_get_default_inter_motion_vector_cost_table_intel = 5720,
    subgroup_avc_mce_get_default_high_penalty_cost_table_intel = 5721,
    subgroup_avc_mce_get_default_medium_penalty_cost_table_intel = 5722,
    subgroup_avc_mce_get_default_low_penalty_cost_table_intel = 5723,
    subgroup_avc_mce_set_motion_vector_cost_function_intel = 5724,
    subgroup_avc_mce_get_default_intra_luma_mode_penalty_intel = 5725,
    subgroup_avc_mce_get_default_non_dc_luma_intra_penalty_intel = 5726,
    subgroup_avc_mce_get_default_intra_chroma_mode_base_penalty_intel = 5727,
    subgroup_avc_mce_set_ac_only_haar_intel = 5728,
    subgroup_avc_mce_set_source_interlaced_field_polarity_intel = 5729,
    subgroup_avc_mce_set_single_reference_interlaced_field_polarity_intel = 5730,
    subgroup_avc_mce_set_dual_reference_interlaced_field_polarities_intel = 5731,
    subgroup_avc_mce_convert_to_ime_payload_intel = 5732,
    subgroup_avc_mce_convert_to_ime_result_intel = 5733,
    subgroup_avc_mce_convert_to_ref_payload_intel = 5734,
    subgroup_avc_mce_convert_to_ref_result_intel = 5735,
    subgroup_avc_mce_convert_to_sic_payload_intel = 5736,
    subgroup_avc_mce_convert_to_sic_result_intel = 5737,
    subgroup_avc_mce_get_motion_vectors_intel = 5738,
    subgroup_avc_mce_get_inter_distortions_intel = 5739,
    subgroup_avc_mce_get_best_inter_distortions_intel = 5740,
    subgroup_avc_mce_get_inter_major_shape_intel = 5741,
    subgroup_avc_mce_get_inter_minor_shape_intel = 5742,
    subgroup_avc_mce_get_inter_directions_intel = 5743,
    subgroup_avc_mce_get_inter_motion_vector_count_intel = 5744,
    subgroup_avc_mce_get_inter_reference_ids_intel = 5745,
    subgroup_avc_mce_get_inter_reference_interlaced_field_polarities_intel = 5746,
    subgroup_avc_ime_initialize_intel = 5747,
    subgroup_avc_ime_set_single_reference_intel = 5748,
    subgroup_avc_ime_set_dual_reference_intel = 5749,
    subgroup_avc_ime_ref_window_size_intel = 5750,
    subgroup_avc_ime_adjust_ref_offset_intel = 5751,
    subgroup_avc_ime_convert_to_mce_payload_intel = 5752,
    subgroup_avc_ime_set_max_motion_vector_count_intel = 5753,
    subgroup_avc_ime_set_unidirectional_mix_disable_intel = 5754,
    subgroup_avc_ime_set_early_search_termination_threshold_intel = 5755,
    subgroup_avc_ime_set_weighted_sad_intel = 5756,
    subgroup_avc_ime_evaluate_with_single_reference_intel = 5757,
    subgroup_avc_ime_evaluate_with_dual_reference_intel = 5758,
    subgroup_avc_ime_evaluate_with_single_reference_streamin_intel = 5759,
    subgroup_avc_ime_evaluate_with_dual_reference_streamin_intel = 5760,
    subgroup_avc_ime_evaluate_with_single_reference_streamout_intel = 5761,
    subgroup_avc_ime_evaluate_with_dual_reference_streamout_intel = 5762,
    subgroup_avc_ime_evaluate_with_single_reference_streaminout_intel = 5763,
    subgroup_avc_ime_evaluate_with_dual_reference_streaminout_intel = 5764,
    subgroup_avc_ime_convert_to_mce_result_intel = 5765,
    subgroup_avc_ime_get_single_reference_streamin_intel = 5766,
    subgroup_avc_ime_get_dual_reference_streamin_intel = 5767,
    subgroup_avc_ime_strip_single_reference_streamout_intel = 5768,
    subgroup_avc_ime_strip_dual_reference_streamout_intel = 5769,
    subgroup_avc_ime_get_streamout_single_reference_major_shape_motion_vectors_intel = 5770,
    subgroup_avc_ime_get_streamout_single_reference_major_shape_distortions_intel = 5771,
    subgroup_avc_ime_get_streamout_single_reference_major_shape_reference_ids_intel = 5772,
    subgroup_avc_ime_get_streamout_dual_reference_major_shape_motion_vectors_intel = 5773,
    subgroup_avc_ime_get_streamout_dual_reference_major_shape_distortions_intel = 5774,
    subgroup_avc_ime_get_streamout_dual_reference_major_shape_reference_ids_intel = 5775,
    subgroup_avc_ime_get_border_reached_intel = 5776,
    subgroup_avc_ime_get_truncated_search_indication_intel = 5777,
    subgroup_avc_ime_get_unidirectional_early_search_termination_intel = 5778,
    subgroup_avc_ime_get_weighting_pattern_minimum_motion_vector_intel = 5779,
    subgroup_avc_ime_get_weighting_pattern_minimum_distortion_intel = 5780,
    subgroup_avc_fme_initialize_intel = 5781,
    subgroup_avc_bme_initialize_intel = 5782,
    subgroup_avc_ref_convert_to_mce_payload_intel = 5783,
    subgroup_avc_ref_set_bidirectional_mix_disable_intel = 5784,
    subgroup_avc_ref_set_bilinear_filter_enable_intel = 5785,
    subgroup_avc_ref_evaluate_with_single_reference_intel = 5786,
    subgroup_avc_ref_evaluate_with_dual_reference_intel = 5787,
    subgroup_avc_ref_evaluate_with_multi_reference_intel = 5788,
    subgroup_avc_ref_evaluate_with_multi_reference_interlaced_intel = 5789,
    subgroup_avc_ref_convert_to_mce_result_intel = 5790,
    subgroup_avc_sic_initialize_intel = 5791,
    subgroup_avc_sic_configure_skc_intel = 5792,
    subgroup_avc_sic_configure_ipe_luma_intel = 5793,
    subgroup_avc_sic_configure_ipe_luma_chroma_intel = 5794,
    subgroup_avc_sic_get_motion_vector_mask_intel = 5795,
    subgroup_avc_sic_convert_to_mce_payload_intel = 5796,
    subgroup_avc_sic_set_intra_luma_shape_penalty_intel = 5797,
    subgroup_avc_sic_set_intra_luma_mode_cost_function_intel = 5798,
    subgroup_avc_sic_set_intra_chroma_mode_cost_function_intel = 5799,
    subgroup_avc_sic_set_bilinear_filter_enable_intel = 5800,
    subgroup_avc_sic_set_skc_forward_transform_enable_intel = 5801,
    subgroup_avc_sic_set_block_based_raw_skip_sad_intel = 5802,
    subgroup_avc_sic_evaluate_ipe_intel = 5803,
    subgroup_avc_sic_evaluate_with_single_reference_intel = 5804,
    subgroup_avc_sic_evaluate_with_dual_reference_intel = 5805,
    subgroup_avc_sic_evaluate_with_multi_reference_intel = 5806,
    subgroup_avc_sic_evaluate_with_multi_reference_interlaced_intel = 5807,
    subgroup_avc_sic_convert_to_mce_result_intel = 5808,
    subgroup_avc_sic_get_ipe_luma_shape_intel = 5809,
    subgroup_avc_sic_get_best_ipe_luma_distortion_intel = 5810,
    subgroup_avc_sic_get_best_ipe_chroma_distortion_intel = 5811,
    subgroup_avc_sic_get_packed_ipe_luma_modes_intel = 5812,
    subgroup_avc_sic_get_ipe_chroma_mode_intel = 5813,
    subgroup_avc_sic_get_packed_skc_luma_count_threshold_intel = 5814,
    subgroup_avc_sic_get_packed_skc_luma_sum_threshold_intel = 5815,
    subgroup_avc_sic_get_inter_raw_sads_intel = 5816,

    variable_length_array_intel = 5818,
    save_memory_intel = 5819,
    restore_memory_intel = 5820,

    arbitrary_float_sin_cos_pi_altera = 5840,
    arbitrary_float_cast_altera = 5841,
    arbitrary_float_cast_from_int_altera = 5842,
    arbitrary_float_cast_to_int_altera = 5843,

    arbitrary_float_add_altera = 5846,
    arbitrary_float_sub_altera = 5847,
    arbitrary_float_mul_altera = 5848,
    arbitrary_float_div_altera = 5849,
    arbitrary_float_gt_altera = 5850,
    arbitrary_float_ge_altera = 5851,
    arbitrary_float_lt_altera = 5852,
    arbitrary_float_le_altera = 5853,
    arbitrary_float_eq_altera = 5854,
    arbitrary_float_recip_altera = 5855,
    arbitrary_float_r_sqrt_altera = 5856,
    arbitrary_float_cbrt_altera = 5857,
    arbitrary_float_hypot_altera = 5858,
    arbitrary_float_sqrt_altera = 5859,
    arbitrary_float_log_intel = 5860,
    arbitrary_float_log2_intel = 5861,
    arbitrary_float_log10_intel = 5862,
    arbitrary_float_log1p_intel = 5863,
    arbitrary_float_exp_intel = 5864,
    arbitrary_float_exp2_intel = 5865,
    arbitrary_float_exp10_intel = 5866,
    arbitrary_float_expm1_intel = 5867,
    arbitrary_float_sin_intel = 5868,
    arbitrary_float_cos_intel = 5869,
    arbitrary_float_sin_cos_intel = 5870,
    arbitrary_float_sin_pi_intel = 5871,
    arbitrary_float_cos_pi_intel = 5872,
    arbitrary_float_a_sin_intel = 5873,
    arbitrary_float_a_sin_pi_intel = 5874,
    arbitrary_float_a_cos_intel = 5875,
    arbitrary_float_a_cos_pi_intel = 5876,
    arbitrary_float_a_tan_intel = 5877,
    arbitrary_float_a_tan_pi_intel = 5878,
    arbitrary_float_a_tan2_intel = 5879,
    arbitrary_float_pow_intel = 5880,
    arbitrary_float_pow_r_intel = 5881,
    arbitrary_float_pow_n_intel = 5882,

    loop_control_intel = 5887,

    alias_domain_decl_intel = 5911,
    alias_scope_decl_intel = 5912,
    alias_scope_list_decl_intel = 5913,

    fixed_sqrt_altera = 5923,
    fixed_recip_altera = 5924,
    fixed_rsqrt_altera = 5925,
    fixed_sin_altera = 5926,
    fixed_cos_altera = 5927,
    fixed_sin_cos_altera = 5928,
    fixed_sin_pi_altera = 5929,
    fixed_cos_pi_altera = 5930,
    fixed_sin_cos_pi_altera = 5931,
    fixed_log_altera = 5932,
    fixed_exp_altera = 5933,
    ptr_cast_to_cross_workgroup_altera = 5934,

    cross_workgroup_cast_to_ptr_altera = 5938,

    read_pipe_blocking_altera = 5946,
    write_pipe_blocking_altera = 5947,

    fpga_reg_altera = 5949,

    ray_query_get_ray_t_min_khr = 6016,
    ray_query_get_ray_flags_khr = 6017,
    ray_query_get_intersection_t_khr = 6018,
    ray_query_get_intersection_instance_custom_index_khr = 6019,
    ray_query_get_intersection_instance_id_khr = 6020,
    ray_query_get_intersection_instance_shader_binding_table_record_offset_khr = 6021,
    ray_query_get_intersection_geometry_index_khr = 6022,
    ray_query_get_intersection_primitive_index_khr = 6023,
    ray_query_get_intersection_barycentrics_khr = 6024,
    ray_query_get_intersection_front_face_khr = 6025,
    ray_query_get_intersection_candidate_aabb_opaque_khr = 6026,
    ray_query_get_intersection_object_ray_direction_khr = 6027,
    ray_query_get_intersection_object_ray_origin_khr = 6028,
    ray_query_get_world_ray_direction_khr = 6029,
    ray_query_get_world_ray_origin_khr = 6030,
    ray_query_get_intersection_object_to_world_khr = 6031,
    ray_query_get_intersection_world_to_object_khr = 6032,

    atomic_f_add_ext = 6035,

    type_buffer_surface_intel = 6086,

    type_struct_continued_intel = 6090,
    constant_composite_continued_intel = 6091,
    spec_constant_composite_continued_intel = 6092,

    composite_construct_continued_intel = 6096,

    convert_f_to_bf16_intel = 6116,
    convert_bf16_to_f_intel = 6117,

    control_barrier_arrive_ext = 6142,
    control_barrier_wait_ext = 6143,

    arithmetic_fence_ext = 6145,

    task_sequence_create_altera = 6163,
    task_sequence_async_altera = 6164,
    task_sequence_get_altera = 6165,
    task_sequence_release_altera = 6166,

    type_task_sequence_altera = 6199,

    subgroup_block_prefetch_intel = 6221,

    subgroup2_d_block_load_intel = 6231,
    subgroup2_d_block_load_transform_intel = 6232,
    subgroup2_d_block_load_transpose_intel = 6233,
    subgroup2_d_block_prefetch_intel = 6234,
    subgroup2_d_block_store_intel = 6235,

    subgroup_matrix_multiply_accumulate_intel = 6237,

    bitwise_function_intel = 6242,

    untyped_variable_length_array_intel = 6244,

    conditional_extension_intel = 6248,
    conditional_entry_point_intel = 6249,
    conditional_capability_intel = 6250,
    spec_constant_target_intel = 6251,
    spec_constant_architecture_intel = 6252,
    spec_constant_capabilities_intel = 6253,
    conditional_copy_object_intel = 6254,

    predicated_load_intel = 6258,
    predicated_store_intel = 6259,

    group_i_mul_khr = 6401,
    group_f_mul_khr = 6402,
    group_bitwise_and_khr = 6403,
    group_bitwise_or_khr = 6404,
    group_bitwise_xor_khr = 6405,
    group_logical_and_khr = 6406,
    group_logical_or_khr = 6407,
    group_logical_xor_khr = 6408,

    round_f_to_tf32_intel = 6426,

    masked_gather_intel = 6428,
    masked_scatter_intel = 6429,

    convert_handle_to_image_intel = 6529,
    convert_handle_to_sampler_intel = 6530,
    convert_handle_to_sampled_image_intel = 6531,

    f_dot2_mix_acc32_valve = 6916,
    f_dot2_mix_acc16_valve = 6917,
    f_dot4_mix_acc32_valve = 6918,

    _,
};

pub const ExecutionModel = enum(u32) {
    vertex = 0,
    tessellation_control = 1,
    tessellation_evaluation = 2,
    geometry = 3,
    fragment = 4,
    gl_compute = 5,
    kernel = 6,
    _,
};

pub const StorageClass = enum(u32) {
    uniform_constant = 0,
    input = 1,
    uniform = 2,
    output = 3,
    workgroup = 4,
    cross_workgroup = 5,
    private = 6,
    function = 7,
    generic = 8,
    push_constant = 9,
    atomic_counter = 10,
    image = 11,
    storage_buffer = 12,
    physical_storage_buffer = 5349,
    _,
};

pub const ExecutionMode = enum(u32) {
    early_fragment_tests = 9,
    local_size = 17,
    _,
};

pub const Decoration = enum(u32) {
    spec_id = 1,
    block = 2,
    buffer_block = 3,
    array_stride = 6,
    built_in = 11,
    location = 30,
    component = 31,
    index = 32,
    binding = 33,
    descriptor_set = 34,
    offset = 35,
    _,
};

pub const Builtin = enum(u32) {
    position = 0,
    point_size = 1,
    clip_distance = 3,
    cull_distance = 4,
    vertex_id = 5,
    instance_id = 6,
    primitive_id = 7,
    invocation_id = 8,
    layer = 9,
    viewport_index = 10,
    tess_level_outer = 11,
    tess_level_inner = 12,
    tess_coord = 13,
    patch_vertices = 14,
    frag_coord = 15,
    point_coord = 16,
    front_facing = 17,
    sample_id = 18,
    sample_position = 19,
    sample_mask = 20,
    frag_depth = 22,
    helper_invocation = 23,
    num_workgroups = 24,
    workgroup_size = 25,
    workgroup_id = 26,
    local_invocation_id = 27,
    global_invocation_id = 28,
    local_invocation_index = 29,
    work_dim = 30,
    global_size = 31,
    enqueued_workgroup_size = 32,
    global_offset = 33,
    global_linear_id = 34,
    subgroup_size = 36,
    subgroup_max_size = 37,
    num_subgroups = 38,
    num_enqueued_subgroups = 39,
    subgroup_id = 40,
    subgroup_local_invocation_id = 41,
    vertex_index = 42,
    instance_index = 43,
    core_id_arm = 4160,
    core_count_arm = 4161,
    core_max_id_arm = 4162,
    warp_id_arm = 4163,
    warp_max_id_arm = 4164,
    subgroup_eq_mask = 4416,
    subgroup_ge_mask = 4417,
    subgroup_gt_mask = 4418,
    subgroup_le_mask = 4419,
    subgroup_lt_mask = 4420,
    base_vertex = 4424,
    base_instance = 4425,
    draw_index = 4426,
    primitive_shading_rate_khr = 4432,
    device_index = 4438,
    view_index = 4440,
    shading_rate_khr = 4444,
    tile_offset_qcom = 4492,
    tile_dimension_qcom = 4493,
    tile_apron_size_qcom = 4494,
    bary_coord_no_persp_amd = 4992,
    bary_coord_no_persp_centroid_amd = 4993,
    bary_coord_no_persp_sample_amd = 4994,
    bary_coord_smooth_amd = 4995,
    bary_coord_smooth_centroid_amd = 4996,
    bary_coord_smooth_sample_amd = 4997,
    bary_coord_pull_model_amd = 4998,
    frag_stencil_ref_ext = 5014,
    remaining_recursion_levels_amdx = 5021,
    shader_index_amdx = 5073,
    sampler_heap_ext = 5122,
    resource_heap_ext = 5123,
    viewport_mask_nv = 5253,
    secondary_position_nv = 5257,
    secondary_viewport_mask_nv = 5258,
    position_per_view_nv = 5261,
    viewport_mask_per_view_nv = 5262,
    fully_covered_ext = 5264,
    task_count_nv = 5274,
    primitive_count_nv = 5275,
    primitive_indices_nv = 5276,
    clip_distance_per_view_nv = 5277,
    cull_distance_per_view_nv = 5278,
    layer_per_view_nv = 5279,
    mesh_view_count_nv = 5280,
    mesh_view_indices_nv = 5281,
    bary_coord_khr = 5286,
    bary_coord_no_persp_khr = 5287,
    frag_size_ext = 5292,
    frag_invocation_count_ext = 5293,
    primitive_point_indices_ext = 5294,
    primitive_line_indices_ext = 5295,
    primitive_triangle_indices_ext = 5296,
    cull_primitive_ext = 5299,
    launch_id_khr = 5319,
    launch_size_khr = 5320,
    world_ray_origin_khr = 5321,
    world_ray_direction_khr = 5322,
    object_ray_origin_khr = 5323,
    object_ray_direction_khr = 5324,
    ray_tmin_khr = 5325,
    ray_tmax_khr = 5326,
    instance_custom_index_khr = 5327,
    object_to_world_khr = 5330,
    world_to_object_khr = 5331,
    hit_t_nv = 5332,
    hit_kind_khr = 5333,
    current_ray_time_nv = 5334,
    hit_triangle_vertex_positions_khr = 5335,
    hit_micro_triangle_vertex_positions_nv = 5337,
    hit_micro_triangle_vertex_barycentrics_nv = 5344,
    incoming_ray_flags_khr = 5351,
    ray_geometry_index_khr = 5352,
    hit_is_sphere_nv = 5359,
    hit_is_lss_nv = 5360,
    hit_sphere_position_nv = 5361,
    warps_per_sm_nv = 5374,
    sm_count_nv = 5375,
    warp_id_nv = 5376,
    sm_id_nv = 5377,
    hit_lss_positions_nv = 5396,
    hit_kind_front_facing_micro_triangle_nv = 5405,
    hit_kind_back_facing_micro_triangle_nv = 5406,
    hit_sphere_radius_nv = 5420,
    hit_lss_radii_nv = 5421,
    cluster_id_nv = 5436,
    cull_mask_khr = 6021,
    _,
};
