const std = @import("std");

const PciInfo = struct {
    id: u16,
    name: []const u8,
    is_discrete: bool,
};

/// Not a hashmap as they need runtime allocations
pub const map = [_]PciInfo{
    .{ .id = 0x1602, .name = "Intel(R) HD Graphics (Broadwell-U)", .is_discrete = false },
    .{ .id = 0x1606, .name = "Intel(R) HD Graphics (Broadwell-U GT1)", .is_discrete = false },
    .{ .id = 0x160a, .name = "Intel(R) HD Graphics (Broadwell-U)", .is_discrete = false },
    .{ .id = 0x160b, .name = "Intel(R) HD Graphics (Broadwell-U)", .is_discrete = false },
    .{ .id = 0x160d, .name = "Intel(R) HD Graphics (Broadwell-U)", .is_discrete = false },
    .{ .id = 0x160e, .name = "Intel(R) HD Graphics (Broadwell-U)", .is_discrete = false },
    .{ .id = 0x1612, .name = "Intel(R) HD Graphics 5600 (Broadwell-H GT2)", .is_discrete = false },
    .{ .id = 0x1616, .name = "Intel(R) HD Graphics 5500 (Broadwell-U GT2)", .is_discrete = false },
    .{ .id = 0x161a, .name = "Intel(R) HD Graphics P5700 (Broadwell-U)", .is_discrete = false },
    .{ .id = 0x161b, .name = "Intel(R) HD Graphics (Broadwell-U)", .is_discrete = false },
    .{ .id = 0x161d, .name = "Intel(R) HD Graphics (Broadwell-U)", .is_discrete = false },
    .{ .id = 0x161e, .name = "Intel(R) HD Graphics 5300 (Broadwell-Y GT2)", .is_discrete = false },
    .{ .id = 0x1622, .name = "Intel(R) Iris(R) Pro Graphics 6200 (Broadwell-DT/H GT3)", .is_discrete = false },
    .{ .id = 0x1626, .name = "Intel(R) HD Graphics 6000 (Broadwell-U GT3)", .is_discrete = false },
    .{ .id = 0x162a, .name = "Intel(R) Iris(R) Pro Graphics P6300 (Broadwell-DT GT3)", .is_discrete = false },
    .{ .id = 0x162b, .name = "Intel(R) Iris(R) Graphics 6100 (Broadwell-U GT3)", .is_discrete = false },
    .{ .id = 0x162d, .name = "Intel(R) HD Graphics (Broadwell-U)", .is_discrete = false },
    .{ .id = 0x162e, .name = "Intel(R) HD Graphics (Broadwell-U)", .is_discrete = false },

    .{ .id = 0x1902, .name = "Intel(R) HD Graphics 510 (Skylake-S GT1)", .is_discrete = false },
    .{ .id = 0x1906, .name = "Intel(R) HD Graphics 510 (Skylake-U GT1)", .is_discrete = false },
    .{ .id = 0x190a, .name = "Intel(R) HD Graphics (Skylake GT1)", .is_discrete = false },
    .{ .id = 0x190b, .name = "Intel(R) HD Graphics 510 (Skylake GT1)", .is_discrete = false },
    .{ .id = 0x190e, .name = "Intel(R) HD Graphics (Skylake GT1)", .is_discrete = false },
    .{ .id = 0x1912, .name = "Intel(R) HD Graphics 530 (Skylake-S GT2)", .is_discrete = false },
    .{ .id = 0x1913, .name = "Intel(R) HD Graphics (Skylake GT1.5)", .is_discrete = false },
    .{ .id = 0x1915, .name = "Intel(R) HD Graphics (Skylake GT1.5)", .is_discrete = false },
    .{ .id = 0x1916, .name = "Intel(R) HD Graphics 520 (Skylake-U GT2)", .is_discrete = false },
    .{ .id = 0x1917, .name = "Intel(R) HD Graphics (Skylake GT2)", .is_discrete = false },
    .{ .id = 0x191a, .name = "Intel(R) HD Graphics (Skylake GT2)", .is_discrete = false },
    .{ .id = 0x191b, .name = "Intel(R) HD Graphics 530 (Skylake-H GT2)", .is_discrete = false },
    .{ .id = 0x191d, .name = "Intel(R) HD Graphics P530 (Skylake-DT/H GT2)", .is_discrete = false },
    .{ .id = 0x191e, .name = "Intel(R) HD Graphics 515 (Skylake-Y GT2)", .is_discrete = false },
    .{ .id = 0x1921, .name = "Intel(R) HD Graphics 520 (Skylake GT2)", .is_discrete = false },
    .{ .id = 0x1923, .name = "Intel(R) HD Graphics 535 (Skylake GT2)", .is_discrete = false },
    .{ .id = 0x1926, .name = "Intel(R) Iris(R) Graphics 540 (Skylake-U GT3)", .is_discrete = false },
    .{ .id = 0x1927, .name = "Intel(R) Iris(R) Graphics 550 (Skylake-U GT3)", .is_discrete = false },
    .{ .id = 0x192a, .name = "Intel(R) HD Graphics (Skylake GT3)", .is_discrete = false },
    .{ .id = 0x192b, .name = "Intel(R) Iris(R) Graphics 555 (Skylake GT3)", .is_discrete = false },
    .{ .id = 0x192d, .name = "Intel(R) Iris(R) Graphics P555 (Skylake-H GT3)", .is_discrete = false },
    .{ .id = 0x1932, .name = "Intel(R) Iris(R) Pro Graphics 580 (Skylake GT4)", .is_discrete = false },
    .{ .id = 0x193a, .name = "Intel(R) Iris(R) Pro Graphics P580 (Skylake-H GT4)", .is_discrete = false },
    .{ .id = 0x193b, .name = "Intel(R) Iris(R) Pro Graphics 580 (Skylake-H GT4)", .is_discrete = false },
    .{ .id = 0x193d, .name = "Intel(R) Iris(R) Pro Graphics P580 (Skylake-H GT4)", .is_discrete = false },

    .{ .id = 0x0a84, .name = "Intel(R) HD Graphics", .is_discrete = false },
    .{ .id = 0x1a84, .name = "Intel(R) HD Graphics", .is_discrete = false },
    .{ .id = 0x1a85, .name = "Intel(R) HD Graphics", .is_discrete = false },
    .{ .id = 0x5a84, .name = "Intel(R) HD Graphics 505 (ApolloLake)", .is_discrete = false },
    .{ .id = 0x5a85, .name = "Intel(R) HD Graphics 500 (ApolloLake GT1)", .is_discrete = false },

    .{ .id = 0x3184, .name = "Intel(R) UHD Graphics 605 (GeminiLake)", .is_discrete = false },
    .{ .id = 0x3185, .name = "Intel(R) UHD Graphics 600 (GeminiLake)", .is_discrete = false },

    .{ .id = 0x5902, .name = "Intel(R) HD Graphics 610 (KabyLake-S GT1)", .is_discrete = false },
    .{ .id = 0x5906, .name = "Intel(R) HD Graphics 610 (KabyLake-U GT1)", .is_discrete = false },
    .{ .id = 0x590a, .name = "Intel(R) HD Graphics (KabyLake GT1)", .is_discrete = false },
    .{ .id = 0x5908, .name = "Intel(R) HD Graphics (KabyLake GT1)", .is_discrete = false },
    .{ .id = 0x590b, .name = "Intel(R) HD Graphics 610 (KabyLake GT1)", .is_discrete = false },
    .{ .id = 0x590e, .name = "Intel(R) HD Graphics (KabyLake GT1)", .is_discrete = false },
    .{ .id = 0x5913, .name = "Intel(R) HD Graphics (KabyLake GT2)", .is_discrete = false },
    .{ .id = 0x5915, .name = "Intel(R) HD Graphics (KabyLake GT2)", .is_discrete = false },
    .{ .id = 0x5917, .name = "Intel(R) UHD Graphics 620 (KabyLake-R GT2)", .is_discrete = false },
    .{ .id = 0x5912, .name = "Intel(R) HD Graphics 630 (KabyLake-S GT2)", .is_discrete = false },
    .{ .id = 0x5916, .name = "Intel(R) HD Graphics 620 (KabyLake-U GT2)", .is_discrete = false },
    .{ .id = 0x591a, .name = "Intel(R) HD Graphics P630 (KabyLake GT2)", .is_discrete = false },
    .{ .id = 0x591b, .name = "Intel(R) HD Graphics 630 (KabyLake-H GT2)", .is_discrete = false },
    .{ .id = 0x591d, .name = "Intel(R) HD Graphics P630 (KabyLake-DT GT2)", .is_discrete = false },
    .{ .id = 0x591e, .name = "Intel(R) HD Graphics 615 (KabyLake-Y GT2)", .is_discrete = false },
    .{ .id = 0x5921, .name = "Intel(R) HD Graphics 620 (KabyLake GT2)", .is_discrete = false },
    .{ .id = 0x5923, .name = "Intel(R) HD Graphics 635 (KabyLake GT2)", .is_discrete = false },
    .{ .id = 0x5926, .name = "Intel(R) Iris(R) Plus Graphics 640 (KabyLake-U GT3)", .is_discrete = false },
    .{ .id = 0x5927, .name = "Intel(R) Iris(R) Plus Graphics 650 (KabyLake-U GT3)", .is_discrete = false },
    .{ .id = 0x593b, .name = "Intel(R) HD Graphics (KabyLake GT2)", .is_discrete = false },

    .{ .id = 0x591c, .name = "Intel(R) UHD Graphics 615 (KabyLake-Y GT2)", .is_discrete = false },
    .{ .id = 0x87c0, .name = "Intel(R) UHD Graphics 617 (AmberLake-Y GT2)", .is_discrete = false },

    .{ .id = 0x87ca, .name = "Intel(R) UHD Graphics 617 (AmberLake-Y GT2)", .is_discrete = false },

    .{ .id = 0x3e90, .name = "Intel(R) UHD Graphics 610 (CoffeeLake-S GT1)", .is_discrete = false },
    .{ .id = 0x3e93, .name = "Intel(R) UHD Graphics 610 (CoffeeLake-S GT1)", .is_discrete = false },
    .{ .id = 0x3e99, .name = "Intel(R) UHD Graphics 610 (CoffeeLake-S GT1)", .is_discrete = false },
    .{ .id = 0x3e9c, .name = "Intel(R) UHD Graphics 610 (CoffeeLake-S GT1)", .is_discrete = false },
    .{ .id = 0x3e91, .name = "Intel(R) UHD Graphics 630 (CoffeeLake-S GT2)", .is_discrete = false },
    .{ .id = 0x3e92, .name = "Intel(R) UHD Graphics 630 (CoffeeLake-S GT2)", .is_discrete = false },
    .{ .id = 0x3e96, .name = "Intel(R) UHD Graphics P630 (CoffeeLake-S GT2)", .is_discrete = false },
    .{ .id = 0x3e98, .name = "Intel(R) UHD Graphics 630 (CoffeeLake-S GT2)", .is_discrete = false },
    .{ .id = 0x3e9a, .name = "Intel(R) UHD Graphics P630 (CoffeeLake-S GT2)", .is_discrete = false },
    .{ .id = 0x3e9b, .name = "Intel(R) UHD Graphics 630 (CoffeeLake-H GT2)", .is_discrete = false },
    .{ .id = 0x3e94, .name = "Intel(R) UHD Graphics P630 (CoffeeLake-S GT2)", .is_discrete = false },
    .{ .id = 0x3ea9, .name = "Intel(R) UHD Graphics 620 (CoffeeLake-U GT2)", .is_discrete = false },
    .{ .id = 0x3ea5, .name = "Intel(R) Iris(R) Plus Graphics 655 (CoffeeLake-U GT3e)", .is_discrete = false },
    .{ .id = 0x3ea6, .name = "Intel(R) Iris(R) Plus Graphics 645 (CoffeeLake-U GT3)", .is_discrete = false },
    .{ .id = 0x3ea7, .name = "Intel(R) HD Graphics (CoffeeLake-U)", .is_discrete = false },
    .{ .id = 0x3ea8, .name = "Intel(R) Iris(R) Plus Graphics 655 (CoffeeLake-U GT3)", .is_discrete = false },

    .{ .id = 0x3ea1, .name = "Intel(R) UHD Graphics 610 (WhiskeyLake-U GT1)", .is_discrete = false },
    .{ .id = 0x3ea4, .name = "Intel(R) UHD Graphics (WhiskeyLake-U)", .is_discrete = false },
    .{ .id = 0x3ea0, .name = "Intel(R) UHD Graphics 620 (WhiskeyLake-U GT2)", .is_discrete = false },
    .{ .id = 0x3ea3, .name = "Intel(R) UHD Graphics (WhiskeyLake-U)", .is_discrete = false },
    .{ .id = 0x3ea2, .name = "Intel(R) UHD Graphics (WhiskeyLake-U)", .is_discrete = false },

    .{ .id = 0x9b21, .name = "Intel(R) UHD Graphics 620 (CometLake-U GT2)", .is_discrete = false },
    .{ .id = 0x9ba0, .name = "Intel(R) UHD Graphics (CometLake GT1)", .is_discrete = false },
    .{ .id = 0x9ba2, .name = "Intel(R) UHD Graphics (CometLake GT1)", .is_discrete = false },
    .{ .id = 0x9ba4, .name = "Intel(R) UHD Graphics 610 (CometLake-H GT1)", .is_discrete = false },
    .{ .id = 0x9ba5, .name = "Intel(R) UHD Graphics 610 (CometLake GT1)", .is_discrete = false },
    .{ .id = 0x9ba8, .name = "Intel(R) UHD Graphics 610 (CometLake-S GT1)", .is_discrete = false },
    .{ .id = 0x9baa, .name = "Intel(R) UHD Graphics (CometLake)", .is_discrete = false },
    .{ .id = 0x9bab, .name = "Intel(R) UHD Graphics (CometLake)", .is_discrete = false },
    .{ .id = 0x9bac, .name = "Intel(R) UHD Graphics (CometLake)", .is_discrete = false },
    .{ .id = 0x9b41, .name = "Intel(R) UHD Graphics (CometLake-U GT2)", .is_discrete = false },
    .{ .id = 0x9bc0, .name = "Intel(R) UHD Graphics (CometLake GT2)", .is_discrete = false },
    .{ .id = 0x9bc2, .name = "Intel(R) UHD Graphics (CometLake GT2)", .is_discrete = false },
    .{ .id = 0x9bc4, .name = "Intel(R) UHD Graphics (CometLake-H GT2)", .is_discrete = false },
    .{ .id = 0x9bc5, .name = "Intel(R) UHD Graphics 630 (CometLake-S GT2)", .is_discrete = false },
    .{ .id = 0x9bc6, .name = "Intel(R) UHD Graphics P630 (CometLake-S GT2)", .is_discrete = false },
    .{ .id = 0x9bc8, .name = "Intel(R) UHD Graphics 630 (CometLake-S GT2)", .is_discrete = false },
    .{ .id = 0x9bca, .name = "Intel(R) UHD Graphics (CometLake)", .is_discrete = false },
    .{ .id = 0x9bcb, .name = "Intel(R) UHD Graphics (CometLake)", .is_discrete = false },
    .{ .id = 0x9bcc, .name = "Intel(R) UHD Graphics (CometLake)", .is_discrete = false },
    .{ .id = 0x9be6, .name = "Intel(R) UHD Graphics P630 (CometLake-S GT2)", .is_discrete = false },
    .{ .id = 0x9bf6, .name = "Intel(R) UHD Graphics P630 (CoffeeLake-S GT2)", .is_discrete = false },

    .{ .id = 0x8a50, .name = "Intel(R) HD Graphics (IceLake)", .is_discrete = false },
    .{ .id = 0x8a51, .name = "Intel(R) Iris(R) Plus Graphics G7 (IceLake GT2)", .is_discrete = false },
    .{ .id = 0x8a52, .name = "Intel(R) Iris(R) Plus Graphics G7 (IceLake GT2)", .is_discrete = false },
    .{ .id = 0x8a53, .name = "Intel(R) Iris(R) Plus Graphics G7 (IceLake GT2)", .is_discrete = false },
    .{ .id = 0x8a54, .name = "Intel(R) Iris(R) Plus Graphics (IceLake GT2)", .is_discrete = false },
    .{ .id = 0x8a56, .name = "Intel(R) UHD Graphics G1 (IceLake GT1)", .is_discrete = false },
    .{ .id = 0x8a57, .name = "Intel(R) HD Graphics (IceLake)", .is_discrete = false },
    .{ .id = 0x8a58, .name = "Intel(R) UHD Graphics G1 (IceLake-Y GT1)", .is_discrete = false },
    .{ .id = 0x8a59, .name = "Intel(R) HD Graphics (IceLake)", .is_discrete = false },
    .{ .id = 0x8a5a, .name = "Intel(R) Iris(R) Plus Graphics G4 (IceLake GT2)", .is_discrete = false },
    .{ .id = 0x8a5b, .name = "Intel(R) HD Graphics (IceLake)", .is_discrete = false },
    .{ .id = 0x8a5c, .name = "Intel(R) Iris(R) Plus Graphics G4 (IceLake GT2)", .is_discrete = false },
    .{ .id = 0x8a5d, .name = "Intel(R) HD Graphics (IceLake)", .is_discrete = false },
    .{ .id = 0x8a71, .name = "Intel(R) HD Graphics (IceLake)", .is_discrete = false },

    .{ .id = 0x4541, .name = "Intel(R) UHD Graphics (ElkhartLake)", .is_discrete = false },
    .{ .id = 0x4551, .name = "Intel(R) UHD Graphics (ElkhartLake)", .is_discrete = false },
    .{ .id = 0x4555, .name = "Intel(R) UHD Graphics Gen11 16EU (ElkhartLake)", .is_discrete = false },
    .{ .id = 0x4557, .name = "Intel(R) UHD Graphics (ElkhartLake)", .is_discrete = false },
    .{ .id = 0x4570, .name = "Intel(R) UHD Graphics (ElkhartLake)", .is_discrete = false },
    .{ .id = 0x4571, .name = "Intel(R) UHD Graphics Gen11 32EU (ElkhartLake)", .is_discrete = false },
    .{ .id = 0x4e51, .name = "Intel(R) UHD Graphics (JasperLake)", .is_discrete = false },
    .{ .id = 0x4e55, .name = "Intel(R) UHD Graphics (JasperLake)", .is_discrete = false },
    .{ .id = 0x4e57, .name = "Intel(R) UHD Graphics (JasperLake)", .is_discrete = false },
    .{ .id = 0x4e61, .name = "Intel(R) UHD Graphics (JasperLake)", .is_discrete = false },
    .{ .id = 0x4e71, .name = "Intel(R) UHD Graphics (JasperLake)", .is_discrete = false },

    .{ .id = 0x4c8a, .name = "Intel(R) UHD Graphics 750 (RocketLake-S GT1)", .is_discrete = false },
    .{ .id = 0x4c8b, .name = "Intel(R) UHD Graphics 730 (RocketLake-S GT1)", .is_discrete = false },
    .{ .id = 0x4c8c, .name = "Intel(R) Graphics (RocketLake-S)", .is_discrete = false },
    .{ .id = 0x4c90, .name = "Intel(R) UHD Graphics P750 (RocketLake-S GT1)", .is_discrete = false },
    .{ .id = 0x4c9a, .name = "Intel(R) UHD Graphics (RocketLake-S)", .is_discrete = false },

    .{ .id = 0x4680, .name = "Intel(R) UHD Graphics 770 (AlderLake-S GT1)", .is_discrete = false },
    .{ .id = 0x4682, .name = "Intel(R) UHD Graphics 730 (AlderLake-S GT1)", .is_discrete = false },
    .{ .id = 0x4688, .name = "Intel(R) UHD Graphics 770 (AlderLake-HX GT1)", .is_discrete = false },
    .{ .id = 0x468a, .name = "Intel(R) UHD Graphics (AlderLake-S)", .is_discrete = false },
    .{ .id = 0x468b, .name = "Intel(R) UHD Graphics (AlderLake-S)", .is_discrete = false },
    .{ .id = 0x4690, .name = "Intel(R) UHD Graphics 770 (AlderLake-S GT1)", .is_discrete = false },
    .{ .id = 0x4692, .name = "Intel(R) UHD Graphics 730 (AlderLake-S GT1)", .is_discrete = false },
    .{ .id = 0x4693, .name = "Intel(R) UHD Graphics 710 (AlderLake-S GT1)", .is_discrete = false },

    .{ .id = 0x4626, .name = "Intel(R) Integrated Graphics Controller (AlderLake-P)", .is_discrete = false },
    .{ .id = 0x4628, .name = "Intel(R) UHD Graphics (AlderLake-UP3 GT2)", .is_discrete = false },
    .{ .id = 0x462a, .name = "Intel(R) UHD Graphics (AlderLake-P)", .is_discrete = false },
    .{ .id = 0x46a0, .name = "Intel(R) Graphics (AlderLake-P GT2)", .is_discrete = false },
    .{ .id = 0x46a1, .name = "Intel(R) UHD Graphics (AlderLake-P)", .is_discrete = false },
    .{ .id = 0x46a2, .name = "Intel(R) Graphics (AlderLake-P)", .is_discrete = false },
    .{ .id = 0x46a3, .name = "Intel(R) UHD Graphics (AlderLake-P GT1)", .is_discrete = false },
    .{ .id = 0x46a6, .name = "Intel(R) Iris(R) Xe Graphics (AlderLake-P GT2)", .is_discrete = false },
    .{ .id = 0x46a8, .name = "Intel(R) Iris(R) Xe Graphics (AlderLake-UP3 GT2)", .is_discrete = false },
    .{ .id = 0x46aa, .name = "Intel(R) Iris(R) Xe Graphics (AlderLake-UP4 GT2)", .is_discrete = false },
    .{ .id = 0x46b0, .name = "Intel(R) Iris(R) Xe Graphics (AlderLake-P)", .is_discrete = false },
    .{ .id = 0x46b1, .name = "Intel(R) Iris(R) Xe Graphics (AlderLake-P)", .is_discrete = false },
    .{ .id = 0x46b2, .name = "Intel(R) Graphics (AlderLake-P)", .is_discrete = false },
    .{ .id = 0x46b3, .name = "Intel(R) UHD Graphics (AlderLake-UP3 GT1)", .is_discrete = false },
    .{ .id = 0x46c0, .name = "Intel(R) Graphics (AlderLake-M GT1)", .is_discrete = false },
    .{ .id = 0x46c1, .name = "Intel(R) Iris(R) Xe Graphics (AlderLake-M)", .is_discrete = false },
    .{ .id = 0x46c2, .name = "Intel(R) Graphics (AlderLake-M)", .is_discrete = false },
    .{ .id = 0x46c3, .name = "Intel(R) UHD Graphics (AlderLake-UP4 GT1)", .is_discrete = false },

    .{ .id = 0x46d0, .name = "Intel(R) UHD Graphics (AlderLake-N)", .is_discrete = false },
    .{ .id = 0x46d1, .name = "Intel(R) UHD Graphics (AlderLake-N)", .is_discrete = false },
    .{ .id = 0x46d2, .name = "Intel(R) UHD Graphics (AlderLake-N)", .is_discrete = false },
    .{ .id = 0x46d3, .name = "Intel(R) Intel Graphics (AlderLake-N)", .is_discrete = false },
    .{ .id = 0x46d4, .name = "Intel(R) Intel Graphics (AlderLake-N)", .is_discrete = false },

    .{ .id = 0x9a40, .name = "Intel(R) Iris(R) Xe Graphics (TigerLake-UP4 GT2)", .is_discrete = false },
    .{ .id = 0x9a49, .name = "Intel(R) Iris(R) Xe Graphics (TigerLake-LP GT2)", .is_discrete = false },
    .{ .id = 0x9a59, .name = "Intel(R) Graphics (TigerLake)", .is_discrete = false },
    .{ .id = 0x9a60, .name = "Intel(R) UHD Graphics (TigerLake-H GT1)", .is_discrete = false },
    .{ .id = 0x9a68, .name = "Intel(R) UHD Graphics (TigerLake-H GT1)", .is_discrete = false },
    .{ .id = 0x9a70, .name = "Intel(R) UHD Graphics (TigerLake-H GT1)", .is_discrete = false },
    .{ .id = 0x9a78, .name = "Intel(R) UHD Graphics G4 (TigerLake-LP GT2)", .is_discrete = false },
    .{ .id = 0x9ac0, .name = "Intel(R) UHD Graphics (TigerLake)", .is_discrete = false },
    .{ .id = 0x9ac9, .name = "Intel(R) UHD Graphics (TigerLake)", .is_discrete = false },
    .{ .id = 0x9ad9, .name = "Intel(R) UHD Graphics (TigerLake)", .is_discrete = false },
    .{ .id = 0x9af8, .name = "Intel(R) UHD Graphics (TigerLake)", .is_discrete = false },

    .{ .id = 0xa780, .name = "Intel(R) UHD Graphics 770 (RaptorLake-S GT1)", .is_discrete = false },
    .{ .id = 0xa781, .name = "Intel(R) UHD Graphics (RaptorLake-S)", .is_discrete = false },
    .{ .id = 0xa782, .name = "Intel(R) UHD Graphics (RaptorLake-S)", .is_discrete = false },
    .{ .id = 0xa783, .name = "Intel(R) UHD Graphics (RaptorLake-S)", .is_discrete = false },
    .{ .id = 0xa788, .name = "Intel(R) UHD Graphics (RaptorLake-S)", .is_discrete = false },
    .{ .id = 0xa789, .name = "Intel(R) UHD Graphics (RaptorLake-S)", .is_discrete = false },
    .{ .id = 0xa78a, .name = "Intel(R) UHD Graphics (RaptorLake-S)", .is_discrete = false },
    .{ .id = 0xa78b, .name = "Intel(R) UHD Graphics (RaptorLake-S)", .is_discrete = false },

    .{ .id = 0xa720, .name = "Intel(R) UHD Graphics (RaptorLake-P)", .is_discrete = false },
    .{ .id = 0xa721, .name = "Intel(R) UHD Graphics (RaptorLake-P)", .is_discrete = false },
    .{ .id = 0xa7a0, .name = "Intel(R) Iris(R) Xe Graphics (RaptorLake-P)", .is_discrete = false },
    .{ .id = 0xa7a1, .name = "Intel(R) Iris(R) Xe Graphics (RaptorLake-P)", .is_discrete = false },
    .{ .id = 0xa7a8, .name = "Intel(R) UHD Graphics (RaptorLake-P)", .is_discrete = false },
    .{ .id = 0xa7a9, .name = "Intel(R) UHD Graphics (RaptorLake-P)", .is_discrete = false },
    .{ .id = 0xa7aa, .name = "Intel(R) Intel Graphics (RaptorLake-P)", .is_discrete = false },
    .{ .id = 0xa7ab, .name = "Intel(R) Intel Graphics (RaptorLake-P)", .is_discrete = false },
    .{ .id = 0xa7ac, .name = "Intel(R) Intel Graphics (RaptorLake-U)", .is_discrete = false },
    .{ .id = 0xa7ad, .name = "Intel(R) Intel Graphics (RaptorLake-U)", .is_discrete = false },

    .{ .id = 0x4905, .name = "Intel(R) Iris(R) Xe MAX Graphics (DG1)", .is_discrete = true },
    .{ .id = 0x4906, .name = "Intel(R) Iris(R) Xe Pod (DG1)", .is_discrete = true },
    .{ .id = 0x4907, .name = "Intel(R) Server GPU SG-18M (SG1)", .is_discrete = true },
    .{ .id = 0x4908, .name = "Intel(R) Iris(R) Xe Graphics (DG1)", .is_discrete = true },
    .{ .id = 0x4909, .name = "Intel(R) Iris(R) Xe MAX 100 (DG1)", .is_discrete = true },

    .{ .id = 0x5690, .name = "Intel(R) Arc(tm) A770M Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x5691, .name = "Intel(R) Arc(tm) A730M Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x5692, .name = "Intel(R) Arc(tm) A550M Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x5693, .name = "Intel(R) Arc(tm) A370M Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x5694, .name = "Intel(R) Arc(tm) A350M Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x5695, .name = "Intel(R) Iris(R) Xe MAX A200M Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x5696, .name = "Intel(R) Arc(tm) A570M Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x5697, .name = "Intel(R) Arc(tm) A530M Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56a0, .name = "Intel(R) Arc(tm) A770 Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56a1, .name = "Intel(R) Arc(tm) A750 Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56a2, .name = "Intel(R) Arc(tm) A580 Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56a3, .name = "Intel(R) Arc(tm) Xe Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56a4, .name = "Intel(R) Arc(tm) Xe Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56a5, .name = "Intel(R) Arc(tm) A380 Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56a6, .name = "Intel(R) Arc(tm) A310 Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56b0, .name = "Intel(R) Arc(tm) Pro A30M Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56b1, .name = "Intel(R) Arc(tm) Pro A40/A50 Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56b2, .name = "Intel(R) Arc(tm) Pro A60M Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56b3, .name = "Intel(R) Arc(tm) Pro A60 Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56ba, .name = "Intel(R) Arc(tm) A380E Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56bb, .name = "Intel(R) Arc(tm) A310E Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56bc, .name = "Intel(R) Arc(tm) A370E Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56bd, .name = "Intel(R) Arc(tm) A350E Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56be, .name = "Intel(R) Arc(tm) A750E Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56bf, .name = "Intel(R) Arc(tm) A580E Graphics (DG2)", .is_discrete = true },
    .{ .id = 0x56c0, .name = "Intel(R) Data Center GPU Flex 170 (ATS-M)", .is_discrete = true },
    .{ .id = 0x56c1, .name = "Intel(R) Data Center GPU Flex 140 (ATS-M)", .is_discrete = true },
    .{ .id = 0x56c2, .name = "Intel(R) Data Center GPU Flex 170V (ATS-M)", .is_discrete = true },

    .{ .id = 0x6420, .name = "Intel(R) Intel Graphics (LunarLake)", .is_discrete = false },
    .{ .id = 0x64a0, .name = "Intel(R) Arc(tm) Graphics 130V/140V (LunarLake)", .is_discrete = false },
    .{ .id = 0x64b0, .name = "Intel(R) Intel Graphics (LunarLake)", .is_discrete = false },

    .{ .id = 0x7d40, .name = "Intel(R) Intel Graphics (MeteorLake-M)", .is_discrete = false },
    .{ .id = 0x7d45, .name = "Intel(R) Intel Graphics (MeteorLake-P)", .is_discrete = false },
    .{ .id = 0x7d55, .name = "Intel(R) Intel Arc Graphics (MeteorLake-P)", .is_discrete = false },
    .{ .id = 0x7d60, .name = "Intel(R) Intel Graphics (MeteorLake-M)", .is_discrete = false },
    .{ .id = 0x7dd5, .name = "Intel(R) Intel Graphics (MeteorLake-P)", .is_discrete = false },

    .{ .id = 0x7d41, .name = "Intel(R) Intel Graphics (ArrowLake-U)", .is_discrete = false },
    .{ .id = 0x7d51, .name = "Intel(R) Arc(tm) Pro 130T/140T Graphics (ArrowLake-P)", .is_discrete = false },
    .{ .id = 0x7d67, .name = "Intel(R) Intel Graphics (ArrowLake-S)", .is_discrete = false },
    .{ .id = 0x7dd1, .name = "Intel(R) Intel Graphics (ArrowLake-P)", .is_discrete = false },
    .{ .id = 0xb640, .name = "Intel(R) Intel Graphics (ArrowLake-H)", .is_discrete = false },

    .{ .id = 0xe202, .name = "Intel(R) Intel Graphics (Battlemage G21)", .is_discrete = true },
    .{ .id = 0xe209, .name = "Intel(R) Intel Graphics (Battlemage G21)", .is_discrete = true },
    .{ .id = 0xe20b, .name = "Intel(R) Arc(tm) B580 Graphics (Battlemage G21)", .is_discrete = true },
    .{ .id = 0xe20c, .name = "Intel(R) Arc(tm) B570 Graphics (Battlemage G21)", .is_discrete = true },
    .{ .id = 0xe20d, .name = "Intel(R) Intel Graphics (Battlemage G21)", .is_discrete = true },
    .{ .id = 0xe210, .name = "Intel(R) Intel Graphics (Battlemage G21)", .is_discrete = true },
    .{ .id = 0xe211, .name = "Intel(R) Arc(tm) Pro B60 Graphics (Battlemage G21)", .is_discrete = true },
    .{ .id = 0xe212, .name = "Intel(R) Arc(tm) Pro B50 Graphics (Battlemage G21)", .is_discrete = true },
    .{ .id = 0xe215, .name = "Intel(R) Intel Graphics (Battlemage G21)", .is_discrete = true },
    .{ .id = 0xe216, .name = "Intel(R) Intel Graphics (Battlemage G21)", .is_discrete = true },
    .{ .id = 0xe220, .name = "Intel(R) Intel Graphics (Battlemage G31)", .is_discrete = true },
    .{ .id = 0xe221, .name = "Intel(R) Intel Graphics (Battlemage G31)", .is_discrete = true },
    .{ .id = 0xe222, .name = "Intel(R) Arc(tm) Pro B65 Graphics (Battlemage G31)", .is_discrete = true },
    .{ .id = 0xe223, .name = "Intel(R) Arc(tm) Pro B70 Graphics (Battlemage G31)", .is_discrete = true },

    .{ .id = 0xb080, .name = "Intel(R) Arc(tm) B390 Graphics (PantherLake)", .is_discrete = false },
    .{ .id = 0xb081, .name = "Intel(R) Arc(tm) B370 Graphics (PantherLake)", .is_discrete = false },
    .{ .id = 0xb082, .name = "Intel(R) Arc(tm) B390 Graphics (PantherLake)", .is_discrete = false },
    .{ .id = 0xb083, .name = "Intel(R) Arc(tm) B370 Graphics (PantherLake)", .is_discrete = false },
    .{ .id = 0xb084, .name = "Intel(R) Arc(tm) Pro B390 Graphics (PantherLake)", .is_discrete = false },
    .{ .id = 0xb085, .name = "Intel(R) Arc(tm) Pro B370 Graphics (PantherLake)", .is_discrete = false },
    .{ .id = 0xb086, .name = "Intel(R) Arc(tm) Pro B390 Graphics (PantherLake)", .is_discrete = false },
    .{ .id = 0xb087, .name = "Intel(R) Arc(tm) Pro B370 Graphics (PantherLake)", .is_discrete = false },
    .{ .id = 0xb08f, .name = "Intel(R) Intel Graphics (PantherLake)", .is_discrete = false },
    .{ .id = 0xb090, .name = "Intel(R) Intel Graphics (PantherLake)", .is_discrete = false },
    .{ .id = 0xb0a0, .name = "Intel(R) Intel Graphics (PantherLake)", .is_discrete = false },
    .{ .id = 0xb0b0, .name = "Intel(R) Intel Graphics (PantherLake)", .is_discrete = false },

    .{ .id = 0xfd80, .name = "Intel(R) Intel Graphics (WildcatLake)", .is_discrete = false },
    .{ .id = 0xfd81, .name = "Intel(R) Intel Graphics (WildcatLake)", .is_discrete = false },

    .{ .id = 0xd740, .name = "Intel(R) Graphics (NVL-S)", .is_discrete = false },
    .{ .id = 0xd741, .name = "Intel(R) Graphics (NVL-U)", .is_discrete = false },
    .{ .id = 0xd742, .name = "Intel(R) Graphics (NVL-H)", .is_discrete = false },
    .{ .id = 0xd743, .name = "Intel(R) Graphics (NVL-HX)", .is_discrete = false },
    .{ .id = 0xd744, .name = "Intel(R) Graphics (NVL-UL)", .is_discrete = false },
    .{ .id = 0xd745, .name = "Intel(R) Graphics (NVL-HX)", .is_discrete = false },

    .{ .id = 0xd750, .name = "Intel(R) Graphics (NVL-P)", .is_discrete = false },
    .{ .id = 0xd751, .name = "Intel(R) Graphics (NVL-P)", .is_discrete = false },
    .{ .id = 0xd752, .name = "Intel(R) Graphics (NVL-P)", .is_discrete = false },
    .{ .id = 0xd753, .name = "Intel(R) Graphics (NVL-P)", .is_discrete = false },
    .{ .id = 0xd754, .name = "Intel(R) Graphics (NVL-P)", .is_discrete = false },
    .{ .id = 0xd755, .name = "Intel(R) Graphics (NVL-P)", .is_discrete = false },
    .{ .id = 0xd756, .name = "Intel(R) Graphics (NVL-P)", .is_discrete = false },
    .{ .id = 0xd757, .name = "Intel(R) Graphics (NVL-P)", .is_discrete = false },
    .{ .id = 0xd75f, .name = "Intel(R) Graphics (NVL-P)", .is_discrete = false },
};
